#!/usr/bin/env ansible-playbook
# vim:ft=ansible :

---
- hosts: all
  vars_files:
    - defaults/main.yml

  tasks:
    - name: install imagemagick package
      become: yes
      apt: name=imagemagick state=present

    - name: include main tasks
      include: tasks/main.yml

    - name: create "exploit.png"
      template:
        src: ./templates/exploit.png.j2
        dest: /tmp/exploit.png

    - name: run injection script
      command: convert exploit.png out.png chdir=/tmp/
      register: run_injection
      ignore_errors: yes

    - name: file check
      stat: path={{ injection_dest }}
      register: filecheck

    - name: result for fixed
      debug: msg="We Fixed It ! :D"
      when: filecheck.stat.exists == false

    - name: result for not yet
      debug: msg="We have vulnerability now. :("
      when: filecheck.stat.exists == true

