#!/usr/bin/env ansible-playbook
# vim:ft=ansible :

---
- hosts: all
  roles:
    - chusiang.vim-and-vi-mode
  vars_files:
    - defaults/main.yml

  tasks:
    - name: install imagemagick package
      become: yes
      apt: name=imagemagick state=present

    - name: include main tasks
      include: tasks/main.yml

