---
#!/usr/bin/env ansible-playbook
# vim:ft=ansible :
# tasks file for CVE-2016-3714.ansible.role

- name: backup "policy.xml"
  become: yes
  command: cp -n {{ policy_path }} {{ policy_path }}.ori

- name: modify "policy.xml"
  become: yes
  template:
    src: ./templates/policy.xml.j2
    dest: "{{ policy_path }}"

- name: create "exploit.png"
  template:
    src: ./templates/exploit.png.j2
    dest: /tmp/exploit.png

- name: run injection script
  command: convert exploit.png out.png chdir=/tmp/
  register: run_injection
  ignore_errors: yes

- name: injection check
  stat: path={{ injection_dest }}
  register: injection_check

- name: result for fixed
  debug: msg="We Fixed It ! :D"
  when: injection_check.stat.exists == false

- name: result for not yet
  debug: msg="We have vulnerability now. :("
  when: injection_check.stat.exists == true

