---
#!/usr/bin/env ansible-playbook
# vim:ft=ansible :
# tasks file for CVE-2016-3714.ansible.role

- debug: msg="==> fix security issue - ImageMagick Command Injection (CVE-2016-3714)"

- name: check file - policy.xml
  stat: path=/etc/ImageMagick/policy.xml
  register: filecheck

- name: backup "policy.xml"
  become: yes
  command: cp -n /etc/ImageMagick/policy.xml /etc/ImageMagick/policy.xml.ori
  when: filecheck.stat.exists

- name: modify "policy.xml"
  become: yes
  template:
    src: ./templates/policy.xml.j2
    dest: /etc/ImageMagick/policy.xml

